# Generated by Django 2.2.1 on 2019-05-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('mpg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cylinders', models.IntegerField()),
                ('displacement', models.IntegerField()),
                ('horsepower', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('acceleration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('model', models.IntegerField()),
                ('origin', models.CharField(max_length=10)),
            ],
        ),
    ]
