# Generated by Django 2.2.1 on 2019-05-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carset',
            name='displacement',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='carset',
            name='horsepower',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='carset',
            name='mpg',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='carset',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
